no need for this

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -203,24 +203,24 @@ server_setup()
       exit 0
     fi
 
-    if [ $? -eq 0 ]
-    then
-     #   while true; do
-     #       printf "${HEAD}Please choose:${END}\n"
-     #       printf "[${INFO}A${END}]dd admin user\n"
-     #       printf "[${INFO}R${END}]eset password\n"
-     #       printf "[${INFO}S${END}]tart server\n"
-     #       printf "[${INFO}Q${END}]uit\n"
-     #       read -p "Add/Reset/Start/Quit? [arsq] " arc
-     #       #case $arc in
-     #       ##    [Aa]* ) add_admin;;
-     #       #    [Rr]* ) reset_pass;;
-     #       #    [Ss]* ) start_server;;
-     #       #    [Qq]* ) break;;
-     #       #    * ) echo "${FAIL}Please answer [A]dd / [R]eset / [S]tart / [Q]uit.${END}\n";;
-     #       #esac
-     #   done
-    fi
+   # if [ $? -eq 0 ]
+   # then
+   #  #   while true; do
+   #  #       printf "${HEAD}Please choose:${END}\n"
+   #  #       printf "[${INFO}A${END}]dd admin user\n"
+   #  #       printf "[${INFO}R${END}]eset password\n"
+   #  #       printf "[${INFO}S${END}]tart server\n"
+   #  #       printf "[${INFO}Q${END}]uit\n"
+   #  #       read -p "Add/Reset/Start/Quit? [arsq] " arc
+   #  #       #case $arc in
+   #  #       ##    [Aa]* ) add_admin;;
+   #  #       #    [Rr]* ) reset_pass;;
+   #  #       #    [Ss]* ) start_server;;
+   #  #       #    [Qq]* ) break;;
+   #  #       #    * ) echo "${FAIL}Please answer [A]dd / [R]eset / [S]tart / [Q]uit.${END}\n";;
+   #  #       #esac
+   #  #   done
+   # fi
 }
 
 add_admin()
